version: '3.9'

volumes:
  influxdb-volume:
  telegraf-volume:

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
        - 8086:8086
    environment:
        - INFLUXDB_DB=ciscomdt
        - INFLUXDB_ADMIN_ENABLED=true
        - INFLUXDB_ADMIN_USER=cisco 
        - INFLUXDB_ADMIN_PASSWORD=Cisco123 
    volumes:
        - influxdb-volume:/var/lib/influxdb:rw
    restart: always

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on: 
        - influxdb
    build:
      context: ./telegraf
    ports:
        - 57500:57500
    volumes:
        - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
        - ./telegraf-volume:/home
    tty: true
    privileged: true
    restart: always

  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana
    ports:
        - 3000:3000
    volumes:
        - ./grafana-volume:/var/lib/grafana
    restart: always
