{
 "title": "Device Health Monitoring",
 "description": "Cisco IOS XE and the Catalyst 9300 switch using the gRPC Dial-Out Model-Driven Telemetry interface to provide basic health and interface monitoring capabilities",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SOURCE",
    "query": "show tag values with key = \"source\""
   },
   {
    "name": "NAME",
    "query": "show tag values with key = \"name\""
   },
   {
    "name": "VRF",
    "query": "show tag values with key = \"vrf\""
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-native:native",
     "select": [
      [
       { "params": [ "version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "PID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-native:native",
     "query": "SELECT \"Cisco_IOS_XE_switch:switch/provision\" FROM \"Cisco-IOS-XE-native:native\" WHERE (\"source\" =~ /^$SOURCE$/) AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "Cisco_IOS_XE_switch:switch/provision"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "Last Boot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openconfig-system:system/state",
     "select": [
      [
       { "params": [ "boot_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openconfig-platform:components/component/fan/state",
     "select": [
      [
       { "params": [ "openconfig_platform_fan:speed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]] $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic",
     "select": [
      [
       { "params": [ "free_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Processor" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 14, "w": 3, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openconfig-platform:components/component/state/temperature",
     "select": [
      [
       { "params": [ "instant" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 14, "w": 3, "x": 21, "y": 1 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]] $col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data",
     "select": [
      [
       { "params": [ "poe_module/available_power" ], "type": "field" }
      ],
      [
       { "params": [ "poe_module/used_power" ], "type": "field" }
      ],
      [
       { "params": [ "poe_switch/consumed_poe_power" ], "type": "field" }
      ],
      [
       { "params": [ "poe_stack/unused_power" ], "type": "field" }
      ],
      [
       { "params": [ "poe_switch/power_budget" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization",
     "select": [
      [
       { "params": [ "five_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Five Seconds" ], "type": "alias" }
      ],
      [
       { "params": [ "one_minute" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "One Minute" ], "type": "alias" }
      ],
      [
       { "params": [ "five_minutes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Five Minutes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]] $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic",
     "select": [
      [
       { "params": [ "used_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Processor" }
     ]
    }
   ]
  },
  {
   "title": "Netflow Performance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Bytes Sent" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-flow-monitor-oper:flow-monitors/flow-export-statistics/export-client/protocol-stats",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Records Dropped" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-flow-monitor-oper:flow-monitors/flow-export-statistics/export-client/protocol-stats",
     "select": [
      [
       { "params": [ "records_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface/QoS Drops",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 15 },
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics",
     "select": [
      [
       { "params": [ "out_discards" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$NAME$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/native/flow/ios-flow:record/ios-flow:match/ios-flow:policy/ios-flow:qos",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cisco-IOS-XE-native:native",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cisco-IOS-XE-native:native",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-native:native",
       "query": "SELECT * FROM \"Cisco-IOS-XE-device-hardware-xe-oper:device-hardware-data\" WHERE (\"source\" =~ /^$SOURCE$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cisco-IOS-XE-cdp-oper:cdp-neighbor-details/cdp-neighbor-detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CDP ",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "measurement": "Cisco-IOS-XE-cdp-oper:cdp-neighbor-details/cdp-neighbor-detail",
       "query": "SELECT * FROM \"Cisco-IOS-XE-cdp-oper:cdp-neighbor-details/cdp-neighbor-detail\" WHERE (\"source\" =~ /^$SOURCE$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "device_name" ], "type": "field" }
        ],
        [
         { "params": [ "ip_address" ], "type": "field" }
        ],
        [
         { "params": [ "local_intf_name" ], "type": "field" }
        ],
        [
         { "params": [ "mgmt_address" ], "type": "field" }
        ],
        [
         { "params": [ "port_id" ], "type": "field" }
        ],
        [
         { "params": [ "platform_name" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-switch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]] $col",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-switch",
       "select": [
        [
         { "params": [ "available_power" ], "type": "field" }
        ],
        [
         { "params": [ "consumed_system_power" ], "type": "field" }
        ],
        [
         { "params": [ "power_budget" ], "type": "field" }
        ],
        [
         { "params": [ "power_allocated" ], "type": "field" }
        ],
        [
         { "params": [ "consumed_poe_power" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    },
    {
     "title": "Power",
     "type": "table",
     "gridPos": { "h": 10, "w": 18, "x": 6, "y": 18 },
     "targets": [
      {
       "alias": "[[tag_name]] $col",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-switch",
       "query": "SELECT * FROM \"Cisco-IOS-XE-poe-oper:poe-oper-data/poe-switch\" WHERE (\"source\" =~ /^$SOURCE$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "available_power" ], "type": "field" }
        ],
        [
         { "params": [ "consumed_system_power" ], "type": "field" }
        ],
        [
         { "params": [ "power_budget" ], "type": "field" }
        ],
        [
         { "params": [ "power_allocated" ], "type": "field" }
        ],
        [
         { "params": [ "consumed_poe_power" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]] $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic",
       "select": [
        [
         { "params": [ "free_memory" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "free" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Processor" }
       ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "table",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 19 },
     "targets": [
      {
       "alias": "[[tag_name]] $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic",
       "query": "SELECT * FROM \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\" WHERE (\"source\" =~ /^$SOURCE$/) AND $timeFilter GROUP BY *",
       "select": [
        [
         { "params": [ "free_memory" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "free" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Processor" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization",
       "select": [
        [
         { "params": [ "five_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Five Seconds" ], "type": "alias" }
        ],
        [
         { "params": [ "one_minute" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "One Minute" ], "type": "alias" }
        ],
        [
         { "params": [ "five_minutes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Five Minutes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU",
     "type": "table",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 6 },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization",
       "query": "SELECT * FROM \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\" WHERE (\"source\" =~ /^$SOURCE$/) AND $timeFilter GROUP BY *",
       "select": [
        [
         { "params": [ "five_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Five Seconds" ], "type": "alias" }
        ],
        [
         { "params": [ "one_minute" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "One Minute" ], "type": "alias" }
        ],
        [
         { "params": [ "five_minutes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Five Minutes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cisco-IOS-XE-matm-oper:matm-oper-data/matm-table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "MAC Address Tab Mapping",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "Cisco-IOS-XE-matm-oper:matm-oper-data/matm-table",
       "query": "SELECT *,last(\"matm_mac_entry/mac\") AS \"matm_mac_entry/port\" FROM \"Cisco-IOS-XE-matm-oper:matm-oper-data/matm-table\" WHERE (\"source\" =~ /^$SOURCE$/) AND $timeFilter GROUP BY *",
       "select": [
        [
         { "params": [ "matm_mac_entry/mac" ], "type": "field" }
        ],
        [
         { "params": [ "matm_mac_entry/mat_addr_type" ], "type": "field" }
        ],
        [
         { "params": [ "matm_mac_entry/port" ], "type": "field" }
        ],
        [
         { "params": [ "matm_mac_entry/table_type" ], "type": "field" }
        ],
        [
         { "params": [ "matm_mac_entry/vlan_id_number" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "/environment-ios-xe-oper:environment-sensors",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor",
       "query": "SELECT * FROM \"Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor\" WHERE (\"source\" =~ /^$SOURCE$/) AND $timeFilter GROUP BY *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cisco-IOS-XE-platform-oper:components/component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "/platform-ios-xe-oper:components",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-platform-oper:components/component",
       "query": "SELECT * FROM \"Cisco-IOS-XE-platform-oper:components/component\" WHERE (\"source\" =~ /^$SOURCE$/) AND $timeFilter GROUP BY *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cisco-IOS-XE-process-memory-oper:memory-usage-processes/memory-usage-process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Memory",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-process-memory-oper:memory-usage-processes/memory-usage-process",
       "query": "SELECT * FROM \"Cisco-IOS-XE-process-memory-oper:memory-usage-processes/memory-usage-process\" WHERE (\"source\" =~ /^$SOURCE$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cisco-IOS-XE-mdt-oper:mdt-oper-data/mdt-subscriptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "MDT",
     "type": "table",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "Cisco-IOS-XE-mdt-oper:mdt-oper-data/mdt-subscriptions",
       "query": "SELECT *, last(\"base/xpath\") AS \"base/xpath\" FROM \"Cisco-IOS-XE-mdt-oper:mdt-oper-data/mdt-subscriptions\" WHERE (\"source\" =~ /^$SOURCE$/) AND $timeFilter GROUP BY *",
       "select": [
        [
         { "params": [ "base/period" ], "type": "field" }
        ],
        [
         { "params": [ "state" ], "type": "field" }
        ],
        [
         { "params": [ "base/stream" ], "type": "field" }
        ],
        [
         { "params": [ "base/encoding" ], "type": "field" }
        ],
        [
         { "params": [ "type" ], "type": "field" }
        ],
        [
         { "params": [ "base/xpath" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cisco-IOS-XE-arp-oper:arp-data/arp-vrf",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "ARP",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "Cisco-IOS-XE-arp-oper:arp-data/arp-vrf",
       "query": "SELECT  * FROM \"Cisco-IOS-XE-arp-oper:arp-data/arp-vrf\" WHERE (\"source\" =~ /^$SOURCE$/ AND \"vrf\" =~ /^$VRF$/) AND $timeFilter ",
       "select": [
        [
         { "params": [ "arp_oper/address" ], "type": "field" }
        ],
        [
         { "params": [ "arp_oper/enctype" ], "type": "field" }
        ],
        [
         { "params": [ "arp_oper/hardware" ], "type": "field" }
        ],
        [
         { "params": [ "arp_oper/hwtype" ], "type": "field" }
        ],
        [
         { "params": [ "arp_oper/interface" ], "type": "field" }
        ],
        [
         { "params": [ "arp_oper/mode" ], "type": "field" }
        ],
        [
         { "params": [ "arp_oper/time" ], "type": "field" }
        ],
        [
         { "params": [ "arp_oper/type" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "vrf", "operator": "=~", "value": "/^$VRF$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cisco-IOS-XE-interfaces-oper:interfaces/interface + Charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Interface Stats",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface",
     "query": "SELECT *,last(\"last_change\") FROM \"Cisco-IOS-XE-interfaces-oper:interfaces/interface\" WHERE (\"source\" =~ /^$SOURCE$/ AND \"name\" =~ /^$NAME$/) AND $timeFilter GROUP BY *",
     "select": [
      [
       { "params": [ "vrf" ], "type": "field" }
      ],
      [
       { "params": [ "admin_status" ], "type": "field" }
      ],
      [
       { "params": [ "interface_type" ], "type": "field" }
      ],
      [
       { "params": [ "oper_status" ], "type": "field" }
      ],
      [
       { "params": [ "phys_address" ], "type": "field" }
      ],
      [
       { "params": [ "description" ], "type": "field" }
      ],
      [
       { "params": [ "mtu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NAME$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface tx-kbps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface",
     "select": [
      [
       { "params": [ "statistics/tx_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$NAME$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface rx-kbps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface",
     "select": [
      [
       { "params": [ "statistics/rx_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$NAME$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "Device Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface",
     "select": [
      [
       { "params": [ "statistics/rx_kbps" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "rx kbps" ], "type": "alias" }
      ],
      [
       { "params": [ "statistics/tx_kbps" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "tx kbps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$NAME$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "Packet Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface",
     "select": [
      [
       { "params": [ "statistics/rx_pps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$NAME$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    },
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface",
     "select": [
      [
       { "params": [ "statistics/tx_pps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$NAME$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
     ]
    }
   ]
  },
  {
   "title": "openconfig-system:system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Openconfig System - System",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openconfig-system:system",
       "query": "SELECT * FROM \"openconfig-system:system\" WHERE (\"source\" =~ /^$SOURCE$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "openconfig-platform:components/component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "OC Platform Components",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openconfig-platform:components/component",
       "query": "SELECT * FROM \"openconfig-platform:components/component\" WHERE (\"source\" =~ /^$SOURCE$/) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "openconfig-interfaces:interfaces/interface/state/counters + Charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "OpenConfig Interfaces",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "measurement": "openconfig-interfaces:interfaces/interface/state/counters",
       "query": "SELECT *,last(\"last_clear\") FROM \"openconfig-interfaces:interfaces/interface/state/counters\" WHERE (\"source\" =~ /^$SOURCE$/ AND \"name\" =~ /^$NAME$/) AND $timeFilter GROUP BY *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NAME$/" }
       ]
      }
     ]
    },
    {
     "title": "Bytes In (OC)",
     "type": "graph",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openconfig-interfaces:interfaces/interface/state/counters",
       "select": [
        [
         { "params": [ "in_octets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NAME$/" }
       ]
      }
     ]
    },
    {
     "title": "Bytes Out (OC)",
     "type": "graph",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openconfig-interfaces:interfaces/interface/state/counters",
       "select": [
        [
         { "params": [ "out_octets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NAME$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Device Bytes In/Out (OC)",
     "type": "graph",
     "gridPos": { "h": 18, "w": 8, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openconfig-interfaces:interfaces/interface/state/counters",
       "select": [
        [
         { "params": [ "in_octets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ "Ingress Bytes" ], "type": "alias" }
        ],
        [
         { "params": [ "out_octets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ "Egress Bytes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    },
    {
     "title": "Packets (OC)",
     "type": "graph",
     "gridPos": { "h": 18, "w": 16, "x": 8, "y": 64 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]] in",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openconfig-interfaces:interfaces/interface/state/counters",
       "select": [
        [
         { "params": [ "in_unicast_pkts" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NAME$/" }
       ]
      },
      {
       "alias": "[[tag_name]] out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openconfig-interfaces:interfaces/interface/state/counters",
       "select": [
        [
         { "params": [ "out_unicast_pkts" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NAME$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "ietf-interfaces:interfaces-state/interface + Charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "IETF Interfaces",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "measurement": "ietf-interfaces:interfaces-state/interface",
       "query": "SELECT *,last(\"phys_address\") FROM \"ietf-interfaces:interfaces-state/interface\" WHERE (\"source\" =~ /^$SOURCE$/ AND \"name\" =~ /^$NAME$/) AND $timeFilter GROUP BY *",
       "select": [
        [
         { "params": [ "statistics/in_octets" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NAME$/" }
       ]
      }
     ]
    },
    {
     "title": "IETF out_octets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ietf-interfaces:interfaces-state/interface",
       "select": [
        [
         { "params": [ "statistics/out_octets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$NAME$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    },
    {
     "title": "IETF in_octets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ietf-interfaces:interfaces-state/interface",
       "select": [
        [
         { "params": [ "statistics/in_octets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$NAME$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}